### ISSUE TITLE
when beforeModel is used in the route the actions won't get picked up

### ISSUE THREAD

**Issue by albertjan** [mschinis/ember-cli-actions#2]
Because the before model is used to hook into the route, when the user implements their own `beforeModel` he/she wont call super, so the code in ActionsMixin won't be called.

You could move the hook into the constructor for a route using `reopen` but then we can't use `routename` to determine the name but you could regex it out of the constructor.

```
this.constructor.toString()
"test-actions-app@route:index:"
```

**Comment by mschinis** [comment]
Hello @albertjan!

Thanks for giving `ember-cli-actions` a spin, and sorry for taking ages to get back!
Above is definitely a valid concern and will get it fixed asap.

v0.1.0 now adds a `manual` mixin that allows you to manually trigger the actions import anywhere you like. I tend to import all my actions in the beforeModel, hence the implementation above.

Just as a reference until I release the documentation, here's an example of how the manual mixin works.

```javascript

import ActionMixin from 'ember-cli-actions/mixins/manual'

export default Ember.Route.extend(ActionMixin, {
    beforeModel(){
        this.importActions('<path_to_actions_file>'); // Imports all actions from the actions file
        this.importActions('<path_to_actions_file>', ['like','follow']); // Imports "like" and "follow" actions from the actions file
    }
});
```

First parameter, `<path_to_actions_file>` can be any valid path, like: `sunflower/actions/shop` or `sunflower/pods/shop/actions`
Second parameter, expects an array of action names to be imported.

You can also do multiple action imports if you like, and they will all be merged in the 'actions' hash for you.

Best,
Michael

**Comment by mschinis** [comment]
Closing since #4 solves this issue!
