### ISSUE TITLE
Deprecation: Using the injected `container` is deprecated.

### ISSUE THREAD

**Issue by albertjan** [mschinis/ember-cli-actions#3]
But it's not as easy to fix as it looks. Because the thing returned from `getOwner` doesn't contain a `lookupFactory` function.

`getOwner(this).__container__.lookupFactory('config:environment')` this does work but you should use the `__container__`.  

@mschinis suggested it may be solved by adding an `InstanceInitializer`

**Comment by mschinis** [comment]
Only just saw this. Closing because your PR fixes it.
